version: '3'

services:
    db-headless:
        container_name: db-headless
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}
            - MYSQL_USER=${WORDPRESS_DB_USER}
        image: mariadb
        ports:
            - '3307:3306'
        volumes: 
            - db_data:/var/lib/mysql
    wp-headless:
        build: .
        command: bash -c 'install_wordpress && apache2-foreground'
        container_name: wp-headless
        depends_on:
            - db-headless
        env_file: ./.env
        ports:
            - '8080:8080'
        user: www-data
        volumes:
            - ./wordpress:/var/www/html
            - ./docker/install_wordpress.sh:/usr/local/bin/install_wordpress
            - ./docker/migratedb_import.sh:/usr/local/bin/migratedb_import
            - ./docker/postlightheadlesswpstarter.wordpress.xml:/var/www/postlightheadlesswpstarter.wordpress.xml
            - ./docker/images:/var/www/images
            - ./docker/plugins:/var/www/plugins
volumes: 
    db_data: